server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-8ssu79i6.sql.tencentcdb.com:23594/springboot_demo
    username: root
    password: geMvVD8n
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

